# CMPS 111 Winter 2017
# MakeFile for asgn2, testing program(s)
# Created by Seongwoo Choi
# Erik Andersen (Team Captain), Seongwoo Choi, Yuzhuang Chen, Michael Cardoza

all : read_test write_test

read_test : 
	cc -o read_test read_test.c  -Wall

write_test : 
	cc -o write_test write_test.c  -Wall

clean :
	rm read_test write_test input output
