# Makefile.dep created Mon Jul 18 00:20:33 PDT 2016
trace.o: trace.cpp trace.h
util.o: util.cpp util.h trace.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc trace.h util.h \
 util.tcc
